// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwqQ0gFwyQzE_bs90zRV_zpQDjI_ghJFQ',
    appId: '1:660836668328:web:8daa28fdf818eb3753c39d',
    messagingSenderId: '660836668328',
    projectId: 'quin-d54e7',
    authDomain: 'quin-d54e7.firebaseapp.com',
    storageBucket: 'quin-d54e7.appspot.com',
    measurementId: 'G-YSSBMHP6JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnddgYhaJ9_It_uNLCTzh68TxkUO_nQBU',
    appId: '1:660836668328:android:826f0d1f9f44497153c39d',
    messagingSenderId: '660836668328',
    projectId: 'quin-d54e7',
    storageBucket: 'quin-d54e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsdfyRuwYqSrYWFkqvjOoGidTLs10ad7s',
    appId: '1:660836668328:ios:133174685b4f8cf153c39d',
    messagingSenderId: '660836668328',
    projectId: 'quin-d54e7',
    storageBucket: 'quin-d54e7.appspot.com',
    iosBundleId: 'com.example.quin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsdfyRuwYqSrYWFkqvjOoGidTLs10ad7s',
    appId: '1:660836668328:ios:6bda41409b1d85a953c39d',
    messagingSenderId: '660836668328',
    projectId: 'quin-d54e7',
    storageBucket: 'quin-d54e7.appspot.com',
    iosBundleId: 'com.example.quin.RunnerTests',
  );
}
